export const CHANGE_BUDGET_INPUT = 'CHANGE_BUDGET_INPUT';
export const CLEAR_INPUT = 'CLEAR_INPUT';

export const ADD_BUDGET = 'ADD_BUDGET';

export const CHANGE_EXPENSE_NAME = 'CHANGE_EXPENSE_NAME';
export const CHANGE_EXPENSE_AMOUNT = 'CHANGE_EXPENSE_AMOUNT';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
